#!/usr/bin/env python3
"""Rebuild INDEX.md from the frontmatter of the skills in vault/.

INDEX.md is the only thing the pick-skills picker reads. Never edit it by hand.

    python3 scripts/build_index.py            # rebuild
    python3 scripts/build_index.py --check    # fail if the index is stale
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from skilllib import find_skill_dirs, parse_frontmatter, repo_root, skill_meta  # noqa: E402

SIDECAR = ".skill-lib.yml"
USAGE = ".skill-lib-usage"  # written by link.py: one date line per link
DESC_LIMIT = 400  # description characters in the index, keeps the index cheap
STATUS_ORDER = ["approved", "trial", "deprecated"]
UPDATED = "Updated:"  # the one line --check ignores


def load_sidecar(skill_dir: Path) -> dict:
    p = skill_dir / SIDECAR
    if not p.exists():
        return {}
    fm, body = parse_frontmatter(p)
    if fm:
        return fm
    # a file without --- is parsed whole as frontmatter
    from skilllib import _mini_yaml  # type: ignore
    return _mini_yaml(p.read_text(encoding="utf-8", errors="replace"))


def read_usage(skill_dir: Path) -> tuple[int, str]:
    """How many times the skill was linked, and when it last was.

    This is the main signal of usefulness: real work is more honest than an eval.
    The Δ from an eval is kept for one case: two similar skills, pick one."""
    p = skill_dir / USAGE
    if not p.exists():
        return 0, ""
    # utf-8-sig: a BOM from a hand edit in a Windows editor would otherwise land
    # in the date and outrank any normal ISO day in max()
    text = p.read_text(encoding="utf-8-sig", errors="replace")
    dates = [x.strip() for x in text.splitlines() if x.strip()]
    return len(dates), (max(dates) if dates else "")


def shorten(text: str, limit: int = DESC_LIMIT) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def collect(root: Path) -> list[dict]:
    vault = root / "vault"
    rows = []
    for d in find_skill_dirs(vault):
        meta = skill_meta(d)
        side = load_sidecar(d)
        meta["status"] = str(side.get("status", "approved")).lower()
        meta["tags"] = side.get("tags") or []
        if isinstance(meta["tags"], str):
            meta["tags"] = [t.strip() for t in meta["tags"].split(",") if t.strip()]
        meta["source"] = side.get("source", "")
        meta["delta"] = side.get("delta", "")
        meta["reviewed"] = side.get("reviewed", "")
        meta["used"], meta["last_used"] = read_usage(d)
        meta["rel"] = d.relative_to(root).as_posix()
        rows.append(meta)
    return rows


def render(rows: list[dict]) -> str:
    counts = {s: sum(1 for r in rows if r["status"] == s) for s in STATUS_ORDER}
    extra = sorted({r["status"] for r in rows} - set(STATUS_ORDER))
    today = dt.date.today().isoformat()

    out = [
        "# INDEX: skill vault",
        "",
        "Generated by `scripts/build_index.py`. Do not edit by hand.",
        "",
        f"{UPDATED} {today} · total: {len(rows)} · "
        + " · ".join(f"{s}: {counts.get(s, 0)}" for s in STATUS_ORDER),
        "",
        "`approved`: reviewed and pays off. `trial`: on probation, "
        "suggest with a caveat. `deprecated`: do not suggest.",
        "",
    ]
    if not rows:
        out += ["_The vault is empty. Add the first skill through `lab/`._", ""]
        return "\n".join(out)

    for status in STATUS_ORDER + extra:
        group = [r for r in rows if r["status"] == status]
        if not group:
            continue
        out.append(f"## {status}")
        out.append("")
        for r in sorted(group, key=lambda x: x["name"]):
            head = f"### {r['name']}"
            if r["tags"]:
                head += f"  `{' · '.join(r['tags'])}`"
            out.append(head)
            desc = shorten(r["description"])
            if r["when_to_use"]:
                desc += " When: " + shorten(r["when_to_use"], 200)
            out.append(desc or "_(no description)_")
            facts = [f"path: `{r['rel']}`", f"{r['lines']} lines", f"hash: {r['hash']}"]
            if r["used"]:
                facts.append(f"linked: {r['used']} · last {r['last_used']}")
            if r["delta"]:
                facts.append(f"Δ {r['delta']}")
            if r["reviewed"]:
                facts.append(f"reviewed: {r['reviewed']}")
            out.append("<sub>" + " · ".join(facts) + "</sub>")
            out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="do not write, only compare")
    ap.add_argument("--root", default=None)
    args = ap.parse_args()

    root = Path(args.root).resolve() if args.root else repo_root()
    rows = collect(root)
    text = render(rows)
    index = root / "INDEX.md"

    if args.check:
        current = index.read_text(encoding="utf-8") if index.exists() else ""
        # the update date changes daily, so compare without it
        norm = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith(UPDATED))
        if norm(current) != norm(text):
            print("INDEX.md is stale: run scripts/build_index.py", file=sys.stderr)
            return 1
        print("INDEX.md is up to date")
        return 0

    # newline="\n" explicitly: on Windows text mode would write CRLF, and the
    # generated index would fight eol=lf from .gitattributes on every build
    with index.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"INDEX.md rebuilt: {len(rows)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
